services:
  prestashop:
    build:
      context: ./.docker/prestashop
      target: dev
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=prestashop
    networks:
      - prestashop-network
    depends_on:
      - mysql

  apache:
    build:
      context: ./.docker/apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - prestashop
    networks:
      - prestashop-network

  mysql:
    image: percona/percona-server:8.0
    container_name: prestashop_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - prestashop-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

networks:
  prestashop-network:
    driver: bridge

volumes:
  mysql_data: 