name: UI tests Product V2
on: [ push, pull_request ]

permissions:
  contents: read   #   to fetch code (actions/checkout)

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TEST_CAMPAIGN: 'sanity:productV2:fast-fail'

jobs:
  sanity:
    permissions:
      contents: read   #   to fetch code (actions/checkout)
    runs-on: ubuntu-22.04
    name: Sanity Product V2
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        timeout-minutes: 15
        uses: ./.github/actions/setup-env
        with:
          PHP_VERSION: ${{ matrix.php }}
          ENABLE_SSL: 'true'
          INSTALL_AUTO: 'true'

      - name: Run Tests
        uses: ./.github/actions/ui-test
        with:
          TEST_CAMPAIGN: ${{ env.TEST_CAMPAIGN }}

      - name: Export docker logs
        if: failure()
        run: |
          mkdir -p ./var/docker-logs
          docker logs my_prestashop_mysql_1 > ./var/docker-logs/mysql.log
          docker logs my_prestashop_prestashop-git_1 > ./var/docker-logs/prestashop.log

      - name: Upload Screenshots and logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: sanity-${{ matrix.php }}
          path: |
            ./tests/UI/screenshots/
            ./var/logs
            ./var/docker-logs
